# Generated by Django 3.2.4 on 2021-07-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210713_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparaciones',
            name='marca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.marca'),
        ),
    ]
